version: '3.8'

services:
  backend:
    build:
      context: ./backend_files
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend_files
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL = "http://backend:7860"
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
